### ISSUE TITLE
Guild Points

### ISSUE THREAD

**Issue by Xeroken04** [OmegaPrivateServer/issues#222]
## Summary

I believe that the trade in value for items are incorrect. I should not have to trade in over 50+ items for 5k guild points. I believe the trade in value is per retail, not per era. 
## Expected Behavior

Values are suppose to be lower
## Current Behavior

I'm getting 64 points per trade in..
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Ashenbubs** [comment]
Which item was this, Xero?

Some items are like this, since era.

My item today was a Copper Ring, which took me 190 trade ins for only 4k points.

![image](https://user-images.githubusercontent.com/61240482/80846315-b0f72980-8c03-11ea-85d9-1b3a673093ab.png)

**Comment by Xeroken04** [comment]
In that picture, the amount turned in is based on RETAIL NOW, not back in era. Even when I played on eden I never turned in 50+ items.

**Comment by Ashenbubs** [comment]
Upon checking various items and their guild points for era, you are correct.  The guild point value per item has always remained the same, however the cap for guild points received appears to be triple that which it once was, which is why it requires more turn ins, allowing people to obtain more GP per day.

I'll use the Copper Ring above as an example:
![image](https://user-images.githubusercontent.com/61240482/80861555-2e07ba80-8c67-11ea-838d-7bc5c34d713e.png)
As you can see, the GP value is still 19, but you can only receive 1200 points daily instead of 3600.

Looks like the daily cap for GP items needs to be lowered, not the amount of GP Value per item.
