### ISSUE TITLE
/heal Emnity incorrect

### ISSUE THREAD

**Issue by Ashenbubs** [OmegaPrivateServer/issues#284]
## Summary

/healing generated too much enmity from recovering HP.

## Expected Behavior

Should generate an incredible small amount of hate.

## Current Behavior

Pulling enmity if resting midfight 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Possible Solution & Detailed Description

scripts\globals\effects\healing.lua
This line:

target:updateEnmityFromCure(target, healHP)
Enmity should be a set amount instead of HealHP (AddEnmity, not UpdateEnmityFromCure)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
The current formula is indeed incorrect. I need to do some research but I hope to have this patched by the next update.

**Comment by zierk** [comment]
This issue is now fixed. Formula has been adjusted. TL;DR: The old formula was basically treating the amount of HP you healed per tick as a casted cure spell enmity wise. Regardless of if you were full HP or not. Enmity from resting(/heal) should now reflect how it was in retail era and players should no longer have to worry about pulling aggro while healing unless they are the only ones on the enmity list. This change will go live in Friday's patch.
