### ISSUE TITLE
Summoner Spirit Pacts don't cast spells

### ISSUE THREAD

**Issue by Syfin1** [OmegaPrivateServer/issues#295]
## Summary

When a spirit is summoned it will only auto attack, even at full mp
## Expected Behavior

When a spirit pact assaults it should cast spells, after doing so there is a delay in which it will cast again.
## Current Behavior

The spirit will only auto attack.
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Possible Solution & Detailed Description

The issue occurs after the pet had previously exhausted its mp and was released and resummoned.  The solution would be to check the code and see if there is a flaw in its actions after being desummoned and somehow not registering that it is back at full mp again.
## Characters

Laci
## Steps to Reproduce

1. Summon pact spirit of your choice and send it in to assault.
2.  After it has run out of mp release it and resummon it and send it in again.
3. Sometimes it will not cast any more spells again, it's not always but it happens very frequently.
4. Try to resummon pet over and over until it will begin using its mp again

## Context

It is an annoyance more than anything.  I will have to try recasting it over and over trying to get it to unbug, someitmes it happens to fix quickly other times it takes a long time.

**Comment by CosmicForge** [comment]
Light Spirits especially don't seem to perform as per-era expectations. They should react to orange and red HP with their highest level cures and curagas.

Also it doesn't seem to require the spirit to be in combat to cast these heals either. They can apparently cast them on alliance members as well.

Here's the wiki page closest to Aug 2008: https://ffxiclopedia.fandom.com/wiki/Light_Spirit?oldid=517179

**Comment by zierk** [comment]
What level was the auto attacking observed? I have seen pacts use magic spells at various different levels and tiers. The Light Spirit curing will need to be researched, but this may be a matter of the spirit's not getting access to spells at the right level or something like that.

**Comment by CosmicForge** [comment]
The auto-attacking instead of casting bug appears at any level. Was observed anywhere from level 11 to 75. The strange part is that the spirits would do this upon being freshly summoned, *sometimes*. So MP shouldn't have been an issue. As far as level summoned, it didn't seem to matter when it bugged out. A level 11 Air Spirit for example should know "Aero" but still would do nothing. A level 75 Thunder Spirit should know up to thunder 4, but still would be summoned and just auto endlessly.

But as said before the temporary fix seems to be to summon an Avatar instead and issue a blood pact command, then resummon the spirit and it will work properly (for awhile).

Sometimes you can even summon a "dud" spirit multiple times in a row before it knows to cast, however.

As for Light Spirit, it was known to actually cast cures *sometimes*, but under wrong situations. EX: it wouldn't cure at all until it took damage itself, then it would cure someone randomly who wasn't even damaged. Very wonky.

Hope this helps
