### ISSUE TITLE
White Mage Reraise

### ISSUE THREAD

**Issue by Beveled47** [OmegaPrivateServer/issues#300]
## Summary
Cannot cast Reraise with white mage current sub

## Expected Behavior
should be able to cast reraise as long as white mage is lvl 25+

## Current Behavior
reraise is not on cast able list while at white mage sub'd 32

## Relevant Wiki Link 
https://ffxiclopedia.fandom.com/wiki/Reraise

## Characters
Beveled
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Ashenbubs** [comment]
Reraise was changed on 4-9-2009 to be a Lv25 WHM spell - In era this spell is a Lv33 WHM spell

https://ffxiclopedia.fandom.com/wiki/Reraise?oldid=574753

**Comment by zierk** [comment]
I use re-raise in the lv 30 capped promys.

Also the bug report says to use wiki links from 2008 or earlier. Spell should be Lv 25 in this era.

(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

**Comment by Ashenbubs** [comment]
Reraise is Lv33 - It was changed to Lv25 in 2009.

This is my client on the AH on Omega, stating the spell is 33 - I do believe if you're using a client from another private server, the client text cannot be updated from the server so it may state otherwise - It shouldn't allow you to cast it though at 25, if so, that's the issue here.  

![image](https://user-images.githubusercontent.com/61240482/87014655-54e0f080-c1c4-11ea-90fe-ecc6141124e1.png)

Here are the patch notes for April 2009:
![image](https://user-images.githubusercontent.com/61240482/87015100-dcc6fa80-c1c4-11ea-9f88-47520ddeef6a.png)

**Comment by zierk** [comment]
So the issue upon further investigation is that the spell in the menu is grayed out in the promys, but the spell still works if you type it. 
![Y7OHVOiSNI](https://user-images.githubusercontent.com/8040548/87018979-b613be80-c1da-11ea-9286-ccefb46403fc.png)
![YE6efYrOmD](https://user-images.githubusercontent.com/8040548/87018983-b8761880-c1da-11ea-898e-d4a72aae1e17.png)

**Comment by Swerve256** [comment]
This is because the client thinks it should be 33, but the Omega DB is set to 25. When you select a spell from the menu the client does a check also. Either the DB needs updated to support lvl 33 or we live with the reduced lvl of the spell.

**Comment by zierk** [comment]
Reraise should only be castable at level 33 in this era.  Submitted a patch fixing this, will go live when next update is pushed. Thank you for reporting this.
