### ISSUE TITLE
Flys disappearing in Valkurm Dunes

### ISSUE THREAD

**Issue by Lilpeoples** [OmegaPrivateServer/issues#307]
## Summary

While fighting mobs in Valkurm Dunes the Flys would disappear as I chase them down.

## Expected Behavior

I unfortunately don't have any screenshots, but while I'm farming for the Fly NM I'm using widescan to check the pops. Even while I am the only person in the zone, the fly would disappear. Not get killed but despawn. It even happened as I sic my pet to attack the mob. The fly would just despawn. This isn't the first time it's happened. But I thought someone had killed the mob. I even asked my LS and they have reported the same behavior taking place.

## Characters

Lilpeoples and Lilpeoplex

**Comment by zierk** [comment]
This is occurring because the allowed roaming area is too small for these mobs. Basically what is happening is the mobs spawn then roam. These flies roam around 20-30 yalms in 1 patrol. If they move outside their "allowed area" the game thinks the mobs need to be despawned (like when you aggro mobs and train them to a zone line). This causes the PH to despawn which results in the NM spawning accidentally. Until this is fixed you'll need to camp the exact spawn point for the PH fly (the one that spawns the furthest south) and kill it before it despawns.
