### ISSUE TITLE
Climbpix Highrise (THF AF Quest) Not Spawning

### ISSUE THREAD

**Issue by LouAndLouie** [OmegaPrivateServer/issues#342]
## Summary

None of the 6x ??? located at the towers in Sauromugue Champaign initiate Climbpix Highrise to spawn.
## Expected Behavior

One of the ??? should spawn Climbpix Highrise.  The "correct" ??? changes every Vanadiel day.
## Current Behavior

Currently, all 6x ??? produce dialogue "It is impossible to climb this wall with your bare hands."  This is the fail dialogue for examining an incorrect ???.
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://ffxiclopedia.fandom.com/wiki/As_Thick_as_Thieves
## Possible Solution & Detailed Description

This quest is a follow up quest in the line of THF AF gear and also a prerequisite quest towards obtaining the rest of the THF AF gear.  
## Characters

Lou / Louie
## Steps to Reproduce

1.
2.
3.
4.

## Context

Flagged "As Thick as Thieves" to start working on THF Artifact armor.  Examined all 6x ??? on Darksday with no spawn of the NM.  There was still plenty of time left during darksday so I checked them all again with no success.  Waited until Firesday and examined all 6x ??? again with no success.

**Comment by ChuckGendron** [comment]
From my experience, the optional part is not optional on Omega. 

OPTIONAL: Talk to her two consorts, Cha Lebagta and Bopa Greso who are just south of Nanaa Mihgo at (J-4), for additional details.

**Comment by zierk** [comment]
Try this again but go talk to the optional NPCs in Windy. It is supposed to be optional but it seems like it is mandatory. I am working on a fix for this because the correct ??? is not truly random by day but is pre-determined per player. If you still find yourself unable to complete this quest put in a GM ticket so we can advance your progress. That way you are not stuck waiting for a bug fix patch.

**Comment by zierk** [comment]
This should be fixed in the next patch.
