### ISSUE TITLE
Puppetmaster pet and attachments

### ISSUE THREAD

**Issue by raventn** [OmegaPrivateServer/issues#47]
Puppetmaster pets are abit off exampel basic pet use rng attack and it should use melee instead.
It does sometimes melee dmg but its very very weak should be abit stronger.
Attachement stoneskin "shock absorber" ability arent working at all.

I still leveling so more report of the job will be coming still need test other frames but atm they impossible to get due server low popularity and crafting materials for the other frames.

**Comment by raventn** [comment]
Edit: pet weapon skillchain arent working.  https://ffxiclopedia.fandom.com/wiki/Pup_Solo_Skillchain

**Comment by Volkaru** [comment]
There are a multitude of PUP issues. 
The AI needs a big overwork. Seems every automaton, even mage frames; Use ranged attacks. They're incredibly weak because they don't have ranged skill, though. The AI will sometimes bug out and spam shield bash, even when not on Valoredge frame. This does not go away until being resummoned. Sometimes this makes spell casting AI not function.

There is also a large amount of attachments in era that will be unobtainable until the fights Pulling The Plug, Pulling The Strings, Scouting the Ashu Talif, Royal Painter Escort, and Targeting the captain are implemented. None of which have any real progress on base DSP. 

A good workaround for this in the meantime so that PUP will be able to function somewhat to it's abilities would be to add the NPC Rararoon into the game. He is out of era, but sold attachments you could get in those fights to PUPs who had reached certain levels of the job for a large sum of gil. You could implement the NPC, and remove any attachments out of era that he sells, leaving the ones that would only be obtainable with those fights, instead obtainable when you reach certain level milestones for the job.
https://ffxiclopedia.fandom.com/wiki/Rararoon

As well as expanding Yoyoroon's stock to include the 5th set of attachments (he currently only stocks the first three) outside of the couple out of era attachments in the 5th (Resistor and Archaic Cell) This would allow up and coming PUPs to purchase some pretty much required to function attachments, without resorting to killing level 80+ Trolls in Mount Zhayolm.
https://ffxiclopedia.fandom.com/wiki/Yoyoroon

That would also open up letting PUP test out those attachments, then the gathered data can be used to make the attachments properly function.

**Comment by OmegaBison** [comment]
Thank you for the detailed list!
