### ISSUE TITLE
BCNM40 Undying Promise: NM Ghul-I-Beaban's melee attack does not increase after each reraise

### ISSUE THREAD

**Issue by dvalderrama89** [OmegaPrivateServer/issues#56]
In this fight the Skeleton NM reraises 4 times, and each time it is supposed to get stronger while also losing 10% of its health. By the time it reaches its 5th life it should be hitting a level 40 paladin for 80+ a hit.
## Expected Behavior

The NM should increase its melee attack power each time it revives itself.
## Current Behavior

The melee attack power seems to be the same as its 1st life throughout the entire fight.
## Possible Solution

I'm not familiar with how melee attack influences the amount of damage that is taken by a player, but I think that it is a linear increase from phase 1 to phase 5. In phase 1 the mob was averaging about 20 points of dmg per hit on a level 40 pld with 261 defense (no food, only protect 2 on, decent gear). Crits were in the high 50s. Phase 5 should do significantly more damage, around 80+ per hit on average with 120+ crits. Please review these youtube videos of the retail version of the fight for reference from a PLDs perspctive.
- https://www.youtube.com/watch?v=FWgEiZKBoVk
- https://www.youtube.com/watch?v=U1TUWnhf7yI
## Steps to Reproduce

1. Obtain Star Orb, travel to Qu'Bia Arena, trade orb, select Undying Promise
2. Enter with PLD in party, buff and engage mob
3. /dance

## Detailed Description

View this recording of the fight from today
- https://www.twitch.tv/videos/526881376 (skip to the 8 minute mark for the last life)
Also note that the chest pops too early, it's not supposed to spawn until after the 5th phase of the NM is dead. Popping the chest ends the fight immediately.

**Comment by OmegaBison** [comment]
Current reraise logic looks like this:

```
  2 function reraiseGhul(mob, reraises, target)
  1     mob:setLocalVar("RERAISES", reraises)
11      mob:setMod(dsp.mod.ATT, 25 * reraises)
  1     mob:setHP(mob:getMaxHP() * (1 - (0.10 * reraises)))
  2     mob:resetAI()
  3     mob:stun(3000)
  4     if target then
  5         mob:updateClaim(target)
  6     end
  7     if reraises == 4 then
  8         mob:getBattlefield():setLocalVar("lootSpawned", 0)
  9     end
 10 end
```

Does the `dsp.mod.ATT` value need to be increased?

**Comment by Simseru** [comment]
Not super experienced with lua or ffxi but from doing the bcnm today it appears to be the following:

Their are 2 issues with the BCNM. Skele not gaining strength(actually loses strength) and box spawning early. 

Issue 1: I don't believe it needs to be increased I believe it is the wrong syntax. It is modifying the attack ~TO~ the number and not adding that number to the existing attack. Which is why it actually gets weaker as attack is agjusted to 25 after the first kill with is a huge decrease in power. 

Using AddMod instead of SetMod should add the new value to the current known value. 

Solution 1:
###11      mob:AddMod(dsp.mod.ATT, 25 * reraises)

Should result

Assuming base attack is 100 and it is adding to current(after each modification) attack:
RR1= 100 + 25 = 125 AP
RR2= 125 + (25 x 2)  = 175 AP
RR3 = 175 + (25 x 3) = 250 AP
RR4 = 250 + (25 x 4) = 350 AP

Solution 2:
###11      mob:AddMod(dsp.mod.ATT, 25)

Should result

Assuming base attack is 100 and it is adding to current(after each modification) attack:
RR1= 100 + 25 = 125 AP
RR2= 125 + 25 = 150 AP
RR3 = 150 + 25 = 175 AP
RR4 = 175 + 25 = 200 AP

Solution 1 may be a much larger power increase then intended if it is supposed to simply grow by 25 per kill.

Issue 2:
This is from the order of operations within the statement. It is performing the 4th Reraise and THEN checking the RR number to spawn the chest which causes the chest to spawn immediately after the 4th RR when the 5th version is brought back to life.
That piece may need to be added somewhere else to check RR# & if Mob is dead. I am assuming their is a piece somewhere that indicates if RR=4 do not RR again. Maybe this needs to be part of that segment?

Would have to look up or play around with the syntax but something like:

  ##if reraises == 4 and allEnemiesDefeated then
  ###mob:getBattlefield():setLocalVar("lootSpawned", 0)
  ##end

**Comment by OmegaBison** [comment]
Fixed. Will go live with next patch.
